sudo: false
dist: trusty
group: stable

language: scala

env:
  global:
    - TRAVIS_JDK=zulu@1.7.222
    - JABBA_HOME=/home/travis/.jabba
  matrix:
    - SCRIPTED_TEST="; mimaReportBinaryIssues; test; proguard"

before_install:
  - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.10.1/install.sh | bash && . ~/.jabba/jabba.sh

install:
  - curl -L --fail https://piccolo.link/sbt-0.13.17.tgz > sbt-0.13.17.tgz
  - tar zxf ./sbt-0.13.17.tgz -C $HOME/
  - export PATH="$HOME/sbt/bin:$PATH"
  - export SBT_OPTS="-Xms2048M -Xmx2048M -Xss2M -XX:MaxPermSize=512M"
  - sbt about
  - $JABBA_HOME/bin/jabba install "$TRAVIS_JDK"
  - export JAVA_HOME="$JABBA_HOME/jdk/$TRAVIS_JDK"
  - export PATH="$JAVA_HOME/bin:$PATH"
  - java -version

# Undo _JAVA_OPTIONS environment variable
before_script:
  - unset _JAVA_OPTIONS

script:
  - sbt -J-XX:ReservedCodeCacheSize=128m "$SCRIPTED_TEST"

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.jabba/jdk
