# Use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

language: scala

addons:
  apt:
    packages:
      - openjdk-6-jdk

# TODO - we'd like to actually test everything, but the process library has a deadlock right now
jdk:
  - openjdk6
#  - oraclejdk7

env:
  matrix:
    - SCRIPTED_TEST="; mimaReportBinaryIssues; test; proguard"

# Undo _JAVA_OPTIONS environment variable
before_script:
  - _JAVA_OPTIONS=

script:
  - sbt -J-XX:ReservedCodeCacheSize=128m "$SCRIPTED_TEST"

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
